const carDrivers = [
  {
    plate: "KBD45D",
    milage: 34500,
    driver: "John Doe",
    Phone: 745242312,
    brand: "Toyota Hilux",
    destination_from: "Kigali",
    destination_to: "Mbabane",
    status: "active",
  },
  {
    plate: "KAA65R",
    milage: 343400,
    driver: "Smith Doe",
    Phone: 45242312,
    brand: "Ford Ranger",
    destination_from: "Nairobi",
    destination_to: "Nyeri",
    status: "active",
  },
  {
    plate: "KZZ90D",
    milage: 12000,
    driver: "John Doe",
    Phone: 745242312,
    brand: "Isuzu",
    destination_from: "Kigali",
    destination_to: "Arusha",
    status: "inactive",
  },
  {
    plate: "KQR123D",
    milage: 10,
    driver: "Jin Dole",
    Phone: 7402312,
    brand: "Jeep",
    destination_from: "Mombasa",
    destination_to: "Mbabane",
    status: "inactive",
  },
  {
    plate: "ABC234D",
    milage: 1700,
    driver: "James Coe",
    Phone: 745312,
    brand: "Harrier",
    destination_from: "Nairobi",
    destination_to: "Mbabane",
    status: "active",
  },
  {
    plate: "KLX234D",
    milage: 24500,
    driver: "Jane Doe",
    Phone: 745632342,
    brand: "Toyota Hilux",
    destination_from: "Kigali",
    destination_to: "Mombasa",
    status: "active",
  },
  {
    plate: "MNB567D",
    milage: 53000,
    driver: "Smith Doe",
    Phone: 45242312,
    brand: "Ford Ranger",
    destination_from: "Nairobi",
    destination_to: "Nyeri",
    status: "inactive",
  },
  {
    plate: "TYU890D",
    milage: 4500,
    driver: "Jin Dole",
    Phone: 7402312,
    brand: "Jeep",
    destination_from: "Mombasa",
    destination_to: "Arusha",
    status: "active",
  },
  {
    plate: "VCX123D",
    milage: 12000,
    driver: "James Coe",
    Phone: 745312,
    brand: "Harrier",
    destination_from: "Nairobi",
    destination_to: "Mbabane",
    status: "inactive",
  },
  {
    plate: "ZXC567D",
    milage: 19000,
    driver: "John Doe",
    Phone: 745242312,
    brand: "Isuzu",
    destination_from: "Kigali",
    destination_to: "Nyeri",
    status: "active",
  },
  {
    plate: "POI345D",
    milage: 23000,
    driver: "Jane Doe",
    Phone: 745632342,
    brand: "Toyota Hilux",
    destination_from: "Kigali",
    destination_to: "Mombasa",
    status: "inactive",
  },
  {
    plate: "ASD567D",
    milage: 67000,
    driver: "Smith Doe",
    Phone: 45242312,
    brand: "Ford Ranger",
    destination_from: "Nairobi",
    destination_to: "Arusha",
    status: "active",
  },
  {
    plate: "GHJ890D",
    milage: 12000,
    driver: "Jin Dole",
    Phone: 7402312,
    brand: "Jeep",
    destination_from: "Mombasa",
    destination_to: "Mbabane",
    status: "inactive",
  },
  {
    plate: "JKL234D",
    milage: 8900,
    driver: "James Coe",
    Phone: 745312,
    brand: "Harrier",
    destination_from: "Nairobi",
    destination_to: "Nyeri",
    status: "active",
  },
  {
    plate: "BNM678D",
    milage: 35000,
    driver: "John Doe",
    Phone: 745242312,
    brand: "Isuzu",
    destination_from: "Kigali",
    destination_to: "Arusha",
    status: "inactive",
  },
  {
    plate: "QWE123D",
    milage: 24500,
    driver: "Jane Doe",
    Phone: 745632342,
    brand: "Toyota Hilux",
    destination_from: "Kigali",
    destination_to: "Mombasa",
    status: "active",
  },
  {
    plate: "RTY567D",
    milage: 15000,
    driver: "Smith Doe",
    Phone: 45242312,
    brand: "Ford Ranger",
    destination_from: "Nairobi",
    destination_to: "Nyeri",
    status: "inactive",
  },
  {
    plate: "UIO890D",
    milage: 4500,
    driver: "Jin Dole",
    Phone: 7402312,
    brand: "Jeep",
    destination_from: "Mombasa",
    destination_to: "Arusha",
    status: "active",
  },
  {
    plate: "DFG123D",
    milage: 60000,
    driver: "James Coe",
    Phone: 745312,
    brand: "Harrier",
    destination_from: "Nairobi",
    destination_to: "Mbabane",
    status: "inactive",
  },
  {
    plate: "HJK345D",
    milage: 89000,
    driver: "John Doe",
    Phone: 745242312,
    brand: "Isuzu",
    destination_from: "Kigali",
    destination_to: "Nyeri",
    status: "active",
  },
  {
    plate: "ZXC678D",
    milage: 7000,
    driver: "Jane Doe",
    Phone: 745632342,
    brand: "Toyota Hilux",
    destination_from: "Kigali",
    destination_to: "Mombasa",
    status: "inactive",
  },
  {
    plate: "VBN345D",
    milage: 123000,
    driver: "Smith Doe",
    Phone: 45242312,
    brand: "Ford Ranger",
    destination_from: "Nairobi",
    destination_to: "Arusha",
    status: "active",
  },
  {
    plate: "MNB678D",
    milage: 9500,
    driver: "Jin Dole",
    Phone: 7402312,
    brand: "Jeep",
    destination_from: "Mombasa",
    destination_to: "Mbabane",
    status: "inactive",
  },
  {
    plate: "QWE890D",
    milage: 12300,
    driver: "James Coe",
    Phone: 745312,
    brand: "Harrier",
    destination_from: "Nairobi",
    destination_to: "Nyeri",
    status: "active",
  },
  {
    plate: "RTY123D",
    milage: 45000,
    driver: "John Doe",
    Phone: 745242312,
    brand: "Isuzu",
    destination_from: "Kigali",
    destination_to: "Arusha",
    status: "inactive",
  },
  {
    plate: "UIO567D",
    milage: 23000,
    driver: "Jane Doe",
    Phone: 745632342,
    brand: "Toyota Hilux",
    destination_from: "Kigali",
    destination_to: "Mombasa",
    status: "active",
  },
  {
    plate: "DFG789D",
    milage: 8000,
    driver: "Smith Doe",
    Phone: 45242312,
    brand: "Ford Ranger",
    destination_from: "Nairobi",
    destination_to: "Nyeri",
    status: "inactive",
  },
  {
    plate: "HJK234D",
    milage: 19000,
    driver: "Jin Dole",
    Phone: 7402312,
    brand: "Jeep",
    destination_from: "Mombasa",
    destination_to: "Arusha",
    status: "active",
  },
  {
    plate: "ASD345D",
    milage: 78000,
    driver: "James Coe",
    Phone: 745312,
    brand: "Harrier",
    destination_from: "Nairobi",
    destination_to: "Mbabane",
    status: "inactive",
  },
  {
    plate: "BNM890D",
    milage: 90000,
    driver: "John Doe",
    Phone: 745242312,
    brand: "Isuzu",
    destination_from: "Kigali",
    destination_to: "Nyeri",
    status: "active",
  },
  {
    plate: "QWE567D",
    milage: 67000,
    driver: "Jane Doe",
    Phone: 745632342,
    brand: "Toyota Hilux",
    destination_from: "Kigali",
    destination_to: "Mombasa",
    status: "inactive",
  },
  {
    plate: "RTY678D",
    milage: 12000,
    driver: "Smith Doe",
    Phone: 45242312,
    brand: "Ford Ranger",
    destination_from: "Nairobi",
    destination_to: "Arusha",
    status: "active",
  },
  {
    plate: "UIO345D",
    milage: 2500,
    driver: "Jin Dole",
    Phone: 7402312,
    brand: "Jeep",
    destination_from: "Mombasa",
    destination_to: "Mbabane",
    status: "inactive",
  },
  {
    plate: "DFG678D",
    milage: 54000,
    driver: "James Coe",
    Phone: 745312,
    brand: "Harrier",
    destination_from: "Nairobi",
    destination_to: "Nyeri",
    status: "active",
  },
  {
    plate: "HJK789D",
    milage: 89000,
    driver: "John Doe",
    Phone: 745242312,
    brand: "Isuzu",
    destination_from: "Kigali",
    destination_to: "Arusha",
    status: "inactive",
  },
  {
    plate: "BNM234D",
    milage: 23000,
    driver: "Jane Doe",
    Phone: 745632342,
    brand: "Toyota Hilux",
    destination_from: "Kigali",
    destination_to: "Mombasa",
    status: "active",
  },
  {
    plate: "QWE890D",
    milage: 8000,
    driver: "Smith Doe",
    Phone: 45242312,
    brand: "Ford Ranger",
    destination_from: "Nairobi",
    destination_to: "Nyeri",
    status: "inactive",
  },
  {
    plate: "RTY234D",
    milage: 17000,
    driver: "Jin Dole",
    Phone: 7402312,
    brand: "Jeep",
    destination_from: "Mombasa",
    destination_to: "Arusha",
    status: "active",
  },
  {
    plate: "UIO567D",
    milage: 67000,
    driver: "James Coe",
    Phone: 745312,
    brand: "Harrier",
    destination_from: "Nairobi",
    destination_to: "Mbabane",
    status: "inactive",
  },
  {
    plate: "DFG789D",
    milage: 12000,
    driver: "John Doe",
    Phone: 745242312,
    brand: "Isuzu",
    destination_from: "Kigali",
    destination_to: "Nyeri",
    status: "active",
  },
  {
    plate: "HJK234D",
    milage: 23000,
    driver: "Jane Doe",
    Phone: 745632342,
    brand: "Toyota Hilux",
    destination_from: "Kigali",
    destination_to: "Mombasa",
    status: "inactive",
  },
  {
    plate: "BNM345D",
    milage: 34000,
    driver: "Smith Doe",
    Phone: 45242312,
    brand: "Ford Ranger",
    destination_from: "Nairobi",
    destination_to: "Arusha",
    status: "active",
  },
  {
    plate: "QWE567D",
    milage: 76000,
    driver: "Jin Dole",
    Phone: 7402312,
    brand: "Jeep",
    destination_from: "Mombasa",
    destination_to: "Mbabane",
    status: "inactive",
  },
  {
    plate: "RTY678D",
    milage: 45000,
    driver: "James Coe",
    Phone: 745312,
    brand: "Harrier",
    destination_from: "Nairobi",
    destination_to: "Nyeri",
    status: "active",
  },
];

export const DummyData = () => {
  return carDrivers;
};
